### ISSUE TITLE
browsing localhost error

### ISSUE THREAD

**Issue by verkaro** [hedyhli/gelim#4]
I get this when browsing my developing gmifs server: gelim localhost

[ERROR] dial tcp: lookup .: No address associated with hostname

I don't know how to trouble shoot this. All I can say is amfora allows local browsing.

BTW I enjoy how this browser functions. There are several reasons but one of my favorites is the "tour" option. Very cool.

**Comment by hedyhli** [comment]
It seems to work if I use `gelim localhost/`. Weird, I'll have a look into this.

**Comment by verkaro** [comment]
You are correct. Using the trailing slash does return a local site just fine. Without the slash, the error above exists.

**Comment by hedyhli** [comment]
Hi, I have tested the latest commit (ae8b926) to work. Please build after pulling latest changes and let me know if you're still having the issue. If you prefer to use tagged versions, I'll let you know when the next release is ready. Thanks for this issue!

**Comment by verkaro** [comment]
Just a follow-up of sorts. Gelim and your Spartan server (spsrv) are both excellent. I am using the combo for my intranet documentation. Kudos.

**Comment by hedyhli** [comment]
Hi, this has been released so I'll mark this issue as resolved. Do follow up if there are any other issues.
